# Header
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Categories: /categories
  Search: /search
rss: /atom.xml

# Content
excerpt_link: Read More

# Miscellaneous
google_analytics:
twitter: straybugs
github: crimx
codepen: straybugs
mail: '%73%74%72%61%79%62%75%67%73%40%67%6D%61%69%6C%2E%63%6F%6D'
weibo: straybugs
rss: atom.xml
google_plus:
fb_admins:
fb_app_id:

# svg icon
icon_symbols: /images/symbol-defs.svg
