# Header
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Categories: /categories
  Search: /search
rss: /atom.xml

cover:
  default: nature-forest-trees-fog-2-portrait.jpg
  home: nature-forest-trees-fog-2-portrait.jpg
  post: nature-forest-trees-fog-2-portrait.jpg
  archives: nature-forest-trees-fog-2-portrait.jpg
  categories: nature-forest-trees-fog-2-portrait.jpg
  tags: nature-forest-trees-fog-2-portrait.jpg

# Content
excerpt_link: Read More

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

category_generator:
  per_page: 10

# Miscellaneous
google_analytics:
twitter: straybugs
github: crimx
codepen: straybugs
mail: '%73%74%72%61%79%62%75%67%73%40%67%6D%61%69%6C%2E%63%6F%6D'
google_plus:
fb_admins:
fb_app_id:

