# Header
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Categories: /categories
  Search: /search

# Content
excerpt_link: Read More

# Miscellaneous
google_analytics: UA-49163616-3
twitter: straybugs
github: crimx
codepen: straybugs
v2ex: StrayBugs
mail: '%73%74%72%61%79%62%75%67%73%40%67%6D%61%69%6C%2E%63%6F%6D'
weibo: straybugs
douban: jaward
zhihu: straybugs
bilibili: 6857144
netease_music:
  name: CRIMX
  playlist: djradio/3480003
rss: atom.xml
google_plus:
fb_admins:
fb_app_id:

# svg icon
icon_symbols: /images/symbol-defs.svg
